timezone: Europe/Helsinki
name: rsaarelm blog
url: https://rsaarelm.github.io

exclude:
    - LICENSE
    - README.md

permalink: /:title/


kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
