timezone: Europe/Helsinki
name: rsaarelm blog
url: http://rsaarelm.github.io
google_analytics: UA-61028325-1

exclude:
    - LICENSE
    - README.md

permalink: /:title/


kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
