on: push
name: Build and deploy blog
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout blog
        uses: actions/checkout@v3.0.0
      - name: Build site to public/
        run: cargo run
      - name: Publish static website
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd public/
          git init --initial-branch=master
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add .

          git commit -m "Deploy ${GITHUB_REPOSITORY} to ${GITHUB_REPOSITORY}:gh-pages"
          git push --force "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
          echo "Deploy complete"
