on: push
name: Build and deploy blog
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout blog
        uses: actions/checkout@v3.0.0
      - name: Build linkstamp
        run: |
          git clone --depth=1 https://github.com/rsaarelm/linkstamp
          cd linkstamp
          cargo build
      - name: Install Zola
        run: |
          wget -q -O - "https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz" \
            | tar xzf - -C /usr/local/bin
      - name: Build static zola site HTML pages to public/
        run: zola build
      - name: Build links to public/ with linkstamp
        run: |
          mkdir -p public/links/
          cd linkstamp
          cargo run < ../links.idm > ../public/links/index.html
          cargo run -- --feed --title="rsaarelm's links" --site-url=https://rsaarelm.github.io/links/ < ../links.idm > ../public/links/feed.xml
      - name: Publish static website
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd public/
          git init --initial-branch=master
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add .

          git commit -m "Deploy ${GITHUB_REPOSITORY} to ${GITHUB_REPOSITORY}:gh-pages"
          git push --force "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
          echo "Deploy complete"
